<?php

use Cissee\WebtreesExt\Http\Controllers\PlaceWithinHierarchy;
use Fisharebest\Webtrees\I18N;
use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Place;
use Fisharebest\Webtrees\Tree;

/**
 * @var string $module
 * @var Tree $tree
 * @var string $action
 * @var string $title
 * @var Place|null $current
 * @var array<PlaceWithinHierarchyBase> $breadcrumbs
 * @var bool $note
 * @var string $content
 * @var bool $showeventslink
 * @var Place $place
 * @var array $nextaction
 */

?>

<div id="place-hierarchy">
    <div class="container">
        <h4><?= $title ?></h4>
        <?php if ($current instanceof PlaceWithinHierarchy) : ?>
          <?php foreach ($current->links() as $links) : ?>
            <div class="row">
              <legend class="col-form-label col-sm-3 wt-page-options-label">
                <?php if ($links->label() !== null) : ?>
                  <?= $links->label() ?>
                <?php endif ?>  
              </legend>
              <div class="col-sm-9 wt-page-options-value">
                <div class="form-check-inline">
                  <?php foreach ($links->links() as $link) : ?>
                    <div>
                      <?php if ($link->icon() !== null) : ?>
                        <?= view($link->icon()) ?>
                      <?php endif ?>  
                      <?= $link->format() ?>
                      &nbsp; <?php //TODO better formatting ?>  
                    </div>
                  <?php endforeach ?>
                </div>
              </div> 
            </div>    
          <?php endforeach ?>
        <?php endif ?>
        <h4>&nbsp;</h4> <?php //TODO better formatting ?>  
        <h5 class="text-center">
            <?php foreach ($breadcrumbs as $item) : ?>
                <?php if ($item instanceof PlaceWithinHierarchy) : ?>
                  <?= $item->additionalLinksHtmlBeforeName() ?>
                <?php endif ?>
                <a href="<?= e($item->url()) ?>" dir="auto"><?= ($item->gedcomName() !== '')?$item->placeName():MoreI18N::xlate('World') ?></a>
                - 
            <?php endforeach ?>

            <?php if ($current instanceof PlaceWithinHierarchy) : ?>
              <?= $current->additionalLinksHtmlBeforeName() ?>
            <?php endif ?>
            <?= ($current->gedcomName() !== '')?$current->placeName():MoreI18N::xlate('World') ?>
        </h5>

        <?= $content ?>

        <div class="text-center">
            <?php if ($showeventslink) : ?>
                <a class="formField" href= <?= e(route('module', ['module' => $module, 'action' => $action, 'tree' => $tree->name(), 'place_id' => $place->id(), 'action2' => 'hierarchy-e'])) ?>>
                    <?= MoreI18N::xlate('View table of events occurring in %s', $place->fullName()) ?>
                </a>
                |
            <?php endif ?>

            <a href="<?= e(route('module', ['module' => $module, 'action' => $action, 'tree' => $tree->name(), 'action2' => key($nextaction)])) ?>">
                <?= current($nextaction) ?>
            </a>
        </div>
    </div>
</div>

