<?php

use Cissee\WebtreesExt\MoreI18N;

?>

<div class="<?= $col_class ?> list_table">
    <div class="row">
        <span class="col list_label mr-1">
            <?= MoreI18N::xlate('Place hierarchy') ?>
        </span>
    </div>
    <div class="row">
        <?php foreach ($columns as $column) : ?>
            <ul class="col list_value_wrap mr-1 list-unstyled">
                <?php foreach ($column as $item) : ?>
                    <li>
                        <?php
                          //[RC] adjusted
                        ?>
                        <?= $item->additionalLinksHtmlBeforeName() ?>
                        <a href="<?= e($item->url()) ?>"><?= $item->placeName() ?></a>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php endforeach ?>
    </div>
</div>
