<?php

use Cissee\WebtreesExt\Http\Controllers\PlaceWithinHierarchy;
use Cissee\WebtreesExt\MoreI18N;

/**
 * @var bool   $showlink
 * @var PlaceWithinHierarchy $place
 * @var string $flag
 * @var int    $id
 * @var string $sidebar_class
 * @var array  $stats
 */
?>

<li class="gchart px-md-2 <?= $sidebar_class ?>" data-id="<?= $id ?>">
    <div class="row label">
        <div class="col" style="word-wrap: break-word">
            <?php
              //[RC] adjusted
            ?>
            <?= $place->additionalLinksHtmlBeforeName() ?>
            <?php if ($showlink) : ?>
                <a href="<?= e($place->url()) ?>">
                    <?= $place->placeName() ?>
                </a>
            <?php else : ?>
                <?= $place->placeName() ?>
            <?php endif ?>
        </div>

        <?php if ($flag) : ?>
            <div class="col-sm-3 align-digits">
                <img class="flag" alt="<?= strip_tags($place->placeName()) ?>" title="<?= strip_tags($place->placeName()) ?>" src="<?= $flag ?>">
            </div>
        <?php endif ?>
    </div>

    <?php if ($sidebar_class === 'unmapped') : ?>
        <div class="row">
            <div class="col-sm-9"><i><?= MoreI18N::xlate('The location of this place is not known.') ?></i></div>
            <div class="col-sm-3 align-digits"><?= view('icons/warning') ?></div>
        </div>
    <?php endif ?>

    <div class="row">
        <div class="col-sm-9"><?= MoreI18N::xlate('Individuals') ?></div>
        <div class="col-sm-3 align-digits"><?= $stats['INDI'] ?></div>
    </div>

    <div class="row">
        <div class="col-sm-9"><?= MoreI18N::xlate('Families') ?></div>
        <div class="col-sm-3 align-digits"><?= $stats['FAM'] ?></div>
    </div>
</li>
