<?php

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Vesta\Model\FactFilter;

/**
 * @var Collection<int,Family>     $famlist
 * @var Collection<int,Individual> $indilist
 * @var Tree                       $tree
 * 
 * //[RC] added
 * @var string                     $placename
 */

$factFilter = new class($placename) implements FactFilter {
    
    //gah painful
    private $placename;

    public function __construct($placename) {
        $this->placename = $placename;
    }
    
    public function filter(Fact $fact): bool {
        return ($this->placename === $fact->place()->gedcomName());
    }
};

?>

<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active<?= $indilist->isEmpty() ? ' text-muted' : '' ?>" data-bs-toggle="tab" role="tab" href="#individuals">
            <?= MoreI18N::xlate('Individuals') ?>
            <?= view('components/badge', ['count' => count($indilist)]) ?>
        </a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link<?= $famlist->isEmpty() ? ' text-muted' : '' ?>" data-bs-toggle="tab" role="tab" href="#families">
            <?= MoreI18N::xlate('Families') ?>
            <?= view('components/badge', ['count' => count($famlist)]) ?>
        </a>
    </li>
    <?php if (false) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#placeHistory">
                <?= I18N::translate('Place history') ?>
            </a>
        </li>
    <?php endif ?>  
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" role="tabpanel" id="individuals">
        <?php if ($indilist->isEmpty()) : ?>
            <p><?= MoreI18N::xlate('No results found.') ?></p>
        <?php else : ?>
            <?= view('lists/individuals-table', [
            'individuals' => $indilist,
            'sosa'        => false,
            'tree'        => $tree,
            ]) ?>
        <?php endif ?>
    </div>

    <div class="tab-pane fade" role="tabpanel" id="families">
        <?php if ($famlist->isEmpty()) : ?>
            <p><?= MoreI18N::xlate('No results found.') ?></p>
        <?php else : ?>
            <?= view('lists/families-table', ['families' => $famlist, 'tree' => $tree]) ?>
        <?php endif ?>
    </div>
    
    <?php if (false) : ?>
        <div class="tab-pane fade" role="tabpanel" id="placeHistory">
            <?= view('lists/place-history', [
                'individuals' => $indilist, 
                'record' => null, 
                'factFilter' => $factFilter,
                'tree' => $tree]) ?>
        </div>
    <?php endif ?>
</div>
