<?php

use Cissee\WebtreesExt\Module\ModuleVestalInterface;
use Cissee\WebtreesExt\MoreI18N;
use Cissee\WebtreesExt\PlaceAsTopLevelRecord;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Tree;
use Vesta\CommonI18N;
use Vesta\Model\FactFilter;
use Vesta\VestaUtils;

/**
 * @var Collection<int,Family>     $famlist
 * @var Collection<int,Individual> $indilist
 * @var Tree                       $tree
 * 
 * //[RC] added
 * @var string                     $placename
 * @var ModuleVestalInterface      $module
 * 
 * //$module must also provide getHelpAction for 'Predecessor'!
 * //$module may also provide preferences for 'RESTRICTED_PLACE_HISTORY'!
 */

$factFilter = new class($placename) implements FactFilter {
    
    //gah painful
    private $placename;

    public function __construct($placename) {
        $this->placename = $placename;
    }
    
    public function filter(Fact $fact): bool {
        return ($this->placename === $fact->place()->gedcomName());
    }
};

?>

<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active<?= $indilist->isEmpty() ? ' text-muted' : '' ?>" data-bs-toggle="tab" role="tab" href="#individuals">
            <?= MoreI18N::xlate('Individuals') ?>
            <?= view('components/badge', ['count' => count($indilist)]) ?>
        </a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link<?= $famlist->isEmpty() ? ' text-muted' : '' ?>" data-bs-toggle="tab" role="tab" href="#families">
            <?= MoreI18N::xlate('Families') ?>
            <?= view('components/badge', ['count' => count($famlist)]) ?>
        </a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" data-bs-toggle="tab" role="tab" href="#placeHistory">
            <?= CommonI18N::placeHistory() ?>
        </a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" role="tabpanel" id="individuals">
        <?php if ($indilist->isEmpty()) : ?>
            <p><?= MoreI18N::xlate('No results found.') ?></p>
        <?php else : ?>
            <?= view('lists/individuals-table', [
            'individuals' => $indilist,
            'sosa'        => false,
            'tree'        => $tree,
            ]) ?>
        <?php endif ?>
    </div>

    <div class="tab-pane fade" role="tabpanel" id="families">
        <?php if ($famlist->isEmpty()) : ?>
            <p><?= MoreI18N::xlate('No results found.') ?></p>
        <?php else : ?>
            <?= view('lists/families-table', ['families' => $famlist, 'tree' => $tree]) ?>
        <?php endif ?>
    </div>
    
    <div class="tab-pane fade" role="tabpanel" id="placeHistory">
        <?php
        //create special top-level _LOC record as reference so ResearchSuggestions can use it!
        //also this also allows to obtain a proper url to return to after editing
        ?>
        <?= view(VestaUtils::vestaViewsNamespace() . '::lists/place-history', [
            'individuals' => $indilist,             
            'record' => new PlaceAsTopLevelRecord($placename, $tree), 
            'factFilter' => $factFilter,
            'tree' => $tree,
            'context' => 'ppm',
            'module' => $module]) ?>
    </div>
</div>

<?php
//for help link (in place-history)
?>
<?= view('modals/ajax') ?>
